#pragma once

#include "NativeGameplayTags.h"

namespace ChopItGameplayTags
{
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run_Bootstrap);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cycle_Day);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cycle_Dusk);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cycle_Night);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cycle_Elite);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cycle_Resolution);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run_VictoryChoice);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run_Infinite);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run_Death);
	CHOPITCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Run_Finished);
}
